import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { Inter } from "next/font/google";

import "@/app/globals.css";
import { ThemeProvider } from "@/components/providers/theme.provider";

const inter = Inter({
  subsets: ["vietnamese"],
  display: "swap",
  preload: true,
  fallback: ["system-ui"],
  variable: "--inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.variable} subpixel-antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            storageKey="wibutime-theme"
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
