import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StickyFooter } from "@/components/layout/footer/StickyFooter";
import { FooterContent } from "@/components/layout/footer/FooterContent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <StickyFooter className="text-neutral-900 dark:text-neutral-100">
          <FooterContent />
        </StickyFooter> */}
      </body>
    </html>
  );
}
